USE [master]
GO

/****** Object:  Database [HospitaDb]    Script Date: 3/26/2020 10:06:47 AM ******/
CREATE DATABASE [HospitaDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HospitaDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HospitaDb.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HospitaDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HospitaDb_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HospitaDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HospitaDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HospitaDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HospitaDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HospitaDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HospitaDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HospitaDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [HospitaDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HospitaDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HospitaDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HospitaDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HospitaDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HospitaDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HospitaDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HospitaDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HospitaDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HospitaDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HospitaDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HospitaDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HospitaDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HospitaDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HospitaDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HospitaDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [HospitaDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HospitaDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HospitaDb] SET  MULTI_USER 
GO

ALTER DATABASE [HospitaDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HospitaDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HospitaDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HospitaDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HospitaDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HospitaDb] SET  READ_WRITE 
GO

